Gossip_presque_final-master/config/routes.rb
Rails.application.routes.draw do
	root 'gossips#index'

  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
	resources :gossips
	resources :users, only: [:new, :create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
end

Gossip_presque_final-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Gossip_presque_final-master/app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

Gossip_presque_final-master/app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user, required: false
    belongs_to :tag_gossip, required: false
    has_many :tags, through: :tag_gossips

		validates :title,
    presence: true

    validates :content,
    presence:true
end

Gossip_presque_final-master/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User", required: false
    belongs_to :recipient, class_name: "User", required: false
end

Gossip_presque_final-master/app/models/session.rb
class Session < ApplicationRecord
end

Gossip_presque_final-master/app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :tag_gossips, required: false
    has_many :gossips, through: :tag_gossips
end

Gossip_presque_final-master/app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
    belongs_to :gossip 
    belongs_to :tag 
end

Gossip_presque_final-master/app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, required: false
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
		has_secure_password
		validates :password,
			presence: true
		validates :email,
			presence: true,
			uniqueness: true
end

Gossip_presque_final-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

Gossip_presque_final-master/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
 def index
		@gossips = Gossip.all
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		post_params = params.require(:gossip).permit(:title, :content)
		@gossip.update(post_params)
		redirect_to gossip_path
	end

	def new
    	if logged_in? == false
      		redirect_to new_session_path
    	else
      		@user = current_user
      		@gossip = Gossip.new
      		@all_tags = Tag.all
    	end
  	end

	def create
		post_params= params.require(:gossip).permit(title:params[:title], content:params[:content])
		@gossip = Gossip.create(post_params)
	end

	def destroy
	    @gossip = Gossip.find(params[:id])
	    @gossip.destroy
	    redirect_to root_path
	end

	def show
		@gossip = Gossip.find(params[:id])
	end
end

Gossip_presque_final-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
    end

  def create
  	user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
    	#sessions[:user_id] = user.id
			redirect_to root_path
		else
    	flash.now[:danger] = 'Invalid email/password combination'
    	render 'new'
    end
   end

	def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

Gossip_presque_final-master/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def home
    @all_gossips = Gossip.all
  end

  def team
	end
end

Gossip_presque_final-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create

        User.create(email: params[:email],first_name:params[:first_name], password:params[:password])
        redirect_to new_session_path

    end

    def destroy
    end


end

Gossip_presque_final-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Gossip_presque_final-master/app/helpers/gossips_helper.rb
module GossipsHelper
end

Gossip_presque_final-master/app/helpers/sessions_helper.rb
module SessionsHelper
	 def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  # retourne true si l'user est loggé
  def logged_in?
    session[:user_id] != nil
  end
end

Gossip_presque_final-master/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Gossip_presque_final-master/app/helpers/user_helper.rb
module UserHelper
end

Gossip_presque_final-master/app/views/gossips/edit.html.erb
<h1 class="display-4">Editer un potin </h1>
<%= form_for @gossip do |f| %>
  <div class="form-group">
      <label>Titre du potin</label>
      <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
      <label>Contennu du potin</label>
      <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
      <button type="submit">Modifier l'article</button>
  </div>
<%end%>

Gossip_presque_final-master/app/views/gossips/index.html.erb
<header>
	<%= link_to "créer un potin", new_gossip_path %>
	<%= link_to "team", team_path %>
	<%= link_to "contact", contact_path %>
	<%= link_to 'déconnection', new_session_path %>
</header>
<h1>Bienvenue mouss' !</h1>
<%@gossips.each_with_index do |gossip, index| %> <!-- <% %> pour executer du ruby dans le html -->
         <div id="cards">  
             <p>
              <div id="author"><%= gossip.title %></div> <!-- <%= %> equivaut au puts de Ruby -->
              <div id="content"><%= gossip.content %></div>
            </p>
                <div><a href="/gossips/<%=index + 1%>">Voir le potin <%= index %></a></div>
            <%end%>
        </div>

<%= link_to "créer un potin", new_gossip_path %>

Gossip_presque_final-master/app/views/gossips/new.html.erb
<header>
  <%= link_to "team", team_path %>
  <%= link_to "contact", contact_path %>
  <%= link_to "home", root_path %>
  <%= link_to 'déconnection', new_session_path %>
</header>


<h1>Créer un nouveau potin !  </h1>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <label>Titre du potin</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Contennu du potin</label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <button type="submit">Modifier l'article</button>
  </div>
<%end%>

Gossip_presque_final-master/app/views/gossips/show.html.erb
<header>
	<%= link_to "créer un potin", new_gossip_path %>
	<%= link_to "team", team_path %>
	<%= link_to "contact", contact_path %>
	<%= link_to "home", root_path %>
	<%= link_to 'déconnection', new_session_path %>
</header>


<p>auteur du potin : <%= @gossip.user.id %></p>
<p>titre du potin : <%= @gossip.title %></p>
<p>contenu du potin : <%= @gossip.content %></p>

<%= link_to "éditer le potin", edit_gossip_path(@gossip) %>
<%= link_to "supprimer le potin", gossip_path(@gossip.id) %>

Gossip_presque_final-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bordeldemerde</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

Gossip_presque_final-master/app/views/static_pages/contact.html.erb
<header>
		<div class="contact"><%= link_to "home", '/' %></div>
		<div class="contact"><%= link_to "team", '/team' %></div>
		</header>

<h1>Nous contacter ?</h1>
<p>Si tu veux continuer a bitcher, c'est par ici que ca se passe :<br />
	Fleur -> 0782575550<br />
	Sellig -> 0606060606<br />
PS : On ne veut que les potins les + croustillants !!!</p>

Gossip_presque_final-master/app/views/static_pages/eachGossips.html.erb
<header>
		<div class="contact"><%= link_to "contact", '/contact' %></div>
		<div class="contact"><%= link_to "home", '/' %></div>
		</header>


<h1>Bienvenue  sur le gossip n° <%= @gossip.id %></h1>

<div id="mmm">
<p>Auteur: <%= @gossip.user.first_name %></p>
<p>Titre : <%= @gossip.title %></p>
<p>Le potiiiin : <%= @gossip.content %></p>
</div>

Gossip_presque_final-master/app/views/static_pages/team.html.erb
<header>
		<div class="contact"><%= link_to "contact", '/contact' %></div>
		<div class="contact"><%= link_to "home", '/' %></div>
		</header>

<h1>Hello world !</h1>
<p>Salut moussaillon ! Nous, c'est la team PLS !<br />
	On est tres heureux de t'accueillir sur notre page de Gossips... Habitues a bitcher autour de grandes pintes, on a decide de creer ce forum pour "ragoter" sur les binches ! Soit donc la/le bienvenue sur cette page, et surtout n'hesite pas a nous envoyr tes meilleures anecdotes et potins sur tes potes completement bourres, ca nous ferait enormement plaiz ! See u mouss' !</p>

Gossip_presque_final-master/app/views/users/new.html.erb
<div class="form-group">
<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag '* Ton futur Login (email) : ' %>
  <%= text_field_tag 'email', nil, class: "form-control" %>
  <br /> <br />

  <%= label_tag ' * Mot de passe : ' %>
  <%= text_field_tag 'password', nil, class: "form-control" %>
  <br /> <br />

  <%= label_tag '* Prénom : ' %>
  <%= text_field_tag 'first_name', nil, class: "form-control" %>
  <br /> <br />

  <%= label_tag '* Nom : ' %>
  <%= text_field_tag 'last_name', nil, class: "form-control" %>
  <br /> <br />
  
  <%= label_tag 'Description : ' %>
  <%= text_area_tag 'description', nil, class: "form-control" %>
  <br /> <br />
  
  <%= label_tag 'Age: ' %>
  <%= text_field_tag 'age', nil, class: "form-control" %>
  <br /> <br />

  <select class="field-tag form-item select-tag" name="city">
  <% City.all.each do |city| %>
  <option value="<%= city.id %>"><%= city.name %></option>
  <% end %>
  </select>

  <%= submit_tag "Valider", class: "btn btn-secondary " %>

<% end %>
</div>